#define RB_02_DISPLAY_TOUCH 1
#define RB_02_DISPLAY_SIZE RB_02_DISPLAY_21
#define RB_LICENSE_TYPE RB_LICENSE_TYPE_COMMUNITY
#define RB_PRODUCT_LINE 5
#define RB_ENABLE_GPS_DIAG 1
#define RB02_ESP_BLUETOOTH 1
#define RB_ENABLE_CONSOLE 1
