#define RB_02_DISPLAY_SIZE RB_02_DISPLAY_28
#define RB_PRODUCT_LINE 2
#define RB_LICENSE_TYPE RB_LICENSE_TYPE_COMMUNITY
#define RB_ENABLE_MAP 1
#define RB_02_ENABLE_EXTERNALMAP 1
#define RB_ENABLE_GPS 1
